/**
 * 分子级注释库 —— 人工策划的专业分子生物学描述
 * NODE_NOTES: 分子功能注释（检测器面板 + 事件兜底）
 * CURATED_EVENTS: 特定分子对的事件描述（"SRC>DST" 键，精确到残基/结构域级别）
 * 数据依据: KEGG hsa pathway 图谱 + 标准生化教科书 (Lehninger / Alberts MBoC)
 */

/** 分子功能注释（键 = 基因符号 / 节点 id） */
export const NODE_NOTES: Record<string, string> = {
  // ============ MAPK 级联 ============
  EGF: '表皮生长因子（53 aa 成熟肽），EGFR 的高亲和力配体（Kd≈1 nM），经胞外分泌后扩散结合受体胞外域。',
  EGFR: 'ErbB 家族受体酪氨酸激酶。配体结合诱导二聚化，胞内激酶域反式自磷酸化（Y992/1045/1068/1148/1173），pY 位点募集 GRB2/Shc/PLCγ 等信号接头。',
  GRB2: '接头蛋白：SH2 域结合受体 pY 位点，两个 SH3 域结合 SOS 的富脯氨酸基序，将 SOS 募集至质膜。',
  SOS1: 'RAS 鸟苷酸交换因子（GEF），催化 RAS GDP→GTP 交换；受 GRB2 膜转位激活（膜定位即激活）。',
  SHC1: '接头蛋白，被 RTK 磷酸化后募集 GRB2，提供额外的信号放大支路。',
  HRAS: '小 GTP酶（189 aa，法尼基化锚定质膜）。GTP 结合态招募 RAF；自身 GTPase 水解回 GDP 关闭信号。',
  KRAS: 'RAS 家族成员，4B 异构体经法尼基化锚定膜内侧。人类肿瘤中突变频率最高的癌基因之一（G12D/G12V/Q61 突变丧失 GTPase 活性）。',
  NRAS: 'RAS 家族成员，功能与 HRAS 类似，黑色素瘤中常见 Q61 突变。',
  RAF1: 'MAPKKK。N 端调节域结合 RAS-GTP 后转位至膜、解除自抑制，磷酸化激活 MEK1/2。',
  BRAF: 'RAF 家族激酶，MEKK 层主要成员；V600E 突变（黑色素瘤 ~50%）使激酶域组成性激活。',
  ARAF: 'RAF 家族成员，激酶活性较弱，主要作为支架协同信号传递。',
  MAP2K1: 'MEK1，双重特异性激酶，磷酸化 ERK 激活环 Thr-Glu-Tyr 基序；是曲美替尼等 MEK 抑制剂靶点。',
  MAP2K2: 'MEK2，与 MEK1 功能冗余，双磷酸化 ERK1/2。',
  MAPK1: 'ERK2，MAPK 级联终端激酶。>200 个底物（ELK1、RSK、c-FOS…），激活后入核驱动即早基因程序。',
  MAPK3: 'ERK1，与 ERK2 高度同源，共同介导增殖/分化信号。',
  MAPK8: 'JNK1，应激活化蛋白激酶，磷酸化 c-JUN（Ser63/73）与 ATF2，介导应激/凋亡响应。',
  MAPK9: 'JNK2，JNK 家族成员，参与炎症与应激信号。',
  MAPK14: 'p38α，应激活化激酶，被 MKK3/6 双磷酸化激活，介导炎症细胞因子产生。',
  ELK1: 'ETS 家族转录因子。ERK 磷酸化 Ser383 后与 SRF 协同结合 c-fos 启动子血清反应元件（SRE）。',
  FOS: 'c-FOS 即早基因，被诱导转录后与 c-JUN 二聚化组成 AP-1，驱动第二轮增殖基因表达。',
  JUN: 'c-JUN，AP-1 组分，被 JNK 磷酸化激活；与 FOS 形成碱性拉链二聚体。',
  MYC: 'c-MYC，螺旋-环-螺旋转录因子，协调核糖体合成、糖酵解与细胞周期进程；多个通路的汇聚靶点。',
  DUSP1: 'MAPK 磷酸酶（MKP-1），去磷酸化 ERK/p38/JNK 的 T-X-Y 基序，构成负反馈环路。',
  ATF2: 'ATF/CREB 家族转录因子，被 JNK/p38 磷酸化（Thr71），与 c-JUN 二聚驱动应激基因。',
  RPS6KA1: 'RSK1，ERK 底物激酶，磷酸化 CREB（Ser133）与 GSK3β，介导 ERK 的核内分支。',
  MKNK1: 'MNK1，ERK/p38 底物，磷酸化 eIF4E 调控翻译起始。',
  TGFB1: 'TGF-β1，25 kDa 同源二聚体细胞因子，绝大多数细胞分泌后以潜伏态（LAP 复合物）存在，激活后结合 TGFBR2。',
  // ============ PI3K-Akt ============
  IGF1: '胰岛素样生长因子-1（70 aa），IGF1R 配体，介导生长激素的促生长效应。',
  INS: '胰岛素，51 aa 双链多肽，结合 INSR 引发代谢级联（ GLUT4 转位、糖原合成）。',
  IGF1R: 'RTK，与 INSR 同源。结合 IGF-1 后自磷酸化激活 IRS 接头 → PI3K 级联。',
  INSR: '胰岛素受体 RTK，自磷酸化后募集 IRS1/2，激活 PI3K-Akt 与 Ras-MAPK 双通路。',
  PIK3CA: 'PI3K 催化亚基 p110α，将 PIP2 磷酸化为 PIP3；肿瘤中常见 E545K/H1047R 功能获得性突变。',
  PIK3R1: 'PI3K 调节亚基 p85，SH2 域结合磷酸化 IRS/RTK，解除对 p110 的自抑制。',
  PDPK1: 'PDK1，磷酸化 Akt 激活环 Thr308（PIP3 募集后发生）。',
  AKT1: 'Akt/PKB 丝苏氨酸激酶。 Thr308(Ser473 完全激活)后磷酸 FOXO/GSK3β/TSC2/BAD，整合存活与代谢。',
  AKT2: 'Akt2，在胰岛素响应组织中主导，介导 GLUT4 转位。',
  PTEN: '双特异性磷酸酶（抑癌基因），使 PIP3 去磷酸化为 PIP2，拮抗 PI3K 信号。',
  FOXO1: 'Forkhead 转录因子，被 Akt 磷酸化（T24/S256/S319）出核滞留胞质，抑制凋亡/糖异生基因。',
  FOXO3: 'FORKHEAD 家族，Akt 底物；去磷酸化态入核激活 BIM/PUMA 等凋亡基因。',
  GSK3B: '组成性活性丝苏氨酸激酶，被 Akt 磷酸化 Ser9 抑制；调控糖原合成酶、β-catenin 与 tau。',
  TSC2: '结节蛋白，TSC1/2 复合物具 GAP 活性，催化 Rheb-GTP→GDP，负调控 mTORC1；被 Akt 磷酸化后失活。',
  RPTOR: 'Raptor，mTORC1 特异亚基，结合 S6K/4E-BP1 的 TOS 基序递呈底物。',
  MTOR: 'PIKK 家族激酶，营养/能量/生长因子信号枢纽；组成 mTORC1(帽依赖翻译) 与 mTORC2(Akt Ser473)。',
  BAD: 'BH3-only 蛋白，非磷酸化态结合 BCL-XL 释放促凋亡信号；被 Akt 磷酸化 Ser136 后结合 14-3-3 失活。',
  MDM2: 'E3 泛素连接酶，p53 主要负调控子；被 Akt 磷酸化后加速 p53 降解。',
  EIF4EBP1: '4E-BP1，eIF4E 结合抑制蛋白；被 mTORC1 逐步磷酸化（Thr37/46→Ser65/Thr70）后释放 eIF4E 启动翻译。',
  RPS6KB1: 'S6K1，mTORC1 底物激酶，磷酸化核糖体蛋白 S6 与 eIF4B，促进翻译机器组装。',
  // ============ JAK-STAT ============
  IL2: '白细胞介素-2，133 aa 四螺旋束细胞因子，T 细胞激活后自分泌，驱动克隆扩增。',
  IL2RB: 'IL-2 受体 β 链（中亲和力），胞内箱 1 域结合 JAK1；与 γc 链共同组成高亲和力受体。',
  IL2RG: 'γc 共享链（ cytokine 受体共有 γ 链），结合 JAK3；X 连锁 SCID 突变位点。',
  IFNG: '干扰素-γ，二聚体细胞因子，由 Th1/NK 细胞产生，激活巨噬细胞抗胞内病原。',
  IFNGR1: 'IFN-γ 受体 α 链，结合配体后与 β 链二聚化，胞内域结合 JAK1。',
  JAK1: 'Janus 激酶，与 I 型细胞因子受体组成性关联；磷酸化受体尾部并激活 STAT。',
  JAK3: 'Janus 激酶，主要表达于造血细胞，与 γc 链结合；JAK3 抑制剂（托法替尼）用于自身免疫病。',
  TYK2: 'Tyk2 激酶，介导 I 型干扰素（IFNAR）与 IL-12 信号。',
  STAT1: '信号转导与转录激活子。IFN-γ 通路中酪氨酸磷酸化后同源二聚，结合 GAS 元件。',
  STAT3: 'STAT 家族成员，被 IL-6 家族细胞因子激活；持续活化与肿瘤炎症微环境相关。',
  STAT5A: 'STAT5，IL-2/GH/EPO 通路的增殖信号执行者；二聚体结合 GAS 元件驱动 Cyclin D2/Bcl-xL。',
  STAT5B: 'STAT5B，与 STAT5A 高度同源，GH-STAT5B 轴缺陷致生长迟滞。',
  SOCS1: '细胞因子信号抑制子（SOCS 家族）：SH2 域结合 JAK 磷酸化位点直接抑制，其 BOX 域募集 E3 泛素连接酶。',
  SOCS3: 'SOCS 家族成员，结合 gp130/IL-6R 胞内磷酸化位点阻断 STAT3 信号。',
  CISH: 'SOCS 家族（CISH），结合 EPO/GH 受体磷酸化位点负调控。',
  // ============ cAMP ============
  ADRB2: 'β2 肾上腺素能受体，7 次跨膜 GPCR。激动剂结合后变构激活 Gs，经 GRK/β-arrestin 脱敏。',
  ADRB1: 'β1 肾上腺素能受体，心脏主导亚型，正性变力/变时效应的药理靶点。',
  GNAS: 'G 蛋白 αs 亚基，结合 GTP 后解离并直接刺激腺苷酸环化酶；GNAS 突变致假性甲状旁腺功能减退。',
  GNAI1: 'Giα，抑制型 G 蛋白 α 亚基，直接抑制 AC 并经 βγ 激活 PLCβ。',
  ADCY3: '腺苷酸环化酶 3，跨膜酶，催化 ATP → 3′,5′-cAMP + PPi。',
  ADCY5: '腺苷酸环化酶 5，心脏/脑表达，受 Gs 激活/Gi 抑制的双重调节。',
  PRKACA: '蛋白激酶 A 催化亚基 α。cAMP 结合调节亚基（PRKAR）后释放催化亚基磷酸化 CREB 等。',
  PRKAR1A: 'PKA 调节亚基 Iα，结合 2 分子 cAMP 后释放催化亚基；Carney 复合征突变位点。',
  CREB1: 'cAMP 响应元件结合蛋白，PKA 磷酸化 Ser133 招募 CBP/p300  coactivator 复合体。',
  PDE4B: 'cAMP 特异性磷酸二酯酶 4，水解 cAMP → 5′-AMP 终止信号；PDE4 抑制剂罗氟司特用于 COPD。',
  RAPGEF3: 'EPAC1，cAMP 鸟苷酸交换因子（非 PKA cAMP 靶点），cAMP 结合后激活 Rap1。',
  RAP1A: '小 GTP酶，EPAC 下游，介导整合素激活与细胞粘附。',
  // ============ 钙信号 ============
  ITPR1: 'IP3 受体 1，ER 膜钙释放通道。IP3 结合 + Ca²⁺ 协同变构开放，四聚体孔道释放 ER 钙库。',
  RYR2: 'Ryanodine 受体 2（心肌），CICR 通道：Ca²⁺ 结合触发大量释放，驱动兴奋-收缩耦联。',
  CALM1: '钙调蛋白，17 kDa EF-hand 钙传感器，4 个 Ca²⁺ 结合位点协同变构，解码钙峰频率。',
  CAMK2A: 'CaMKIIα，十二聚体激酶。Ca²⁺/CaM 激活后 Thr286 自磷酸化获得自主活性（LTP 分子开关）。',
  CAMK2D: 'CaMKIIδ，心脏/脑表达，磷酸化 PLB/RyR2 调控钙循环。',
  CAMKK2: 'CaMKKβ，Ca²⁺/CaM 激活后磷酸化 AMPK α 亚基 Thr172（能量-钙信号交叉节点）。',
  PPP3CA: 'Calcineurin Aα，Ca²⁺/CaM 依赖的丝苏氨酸磷酸酶，去磷酸化 NFAT 使其入核（环孢素靶点）。',
  NFATC1: '活化 T 细胞核因子，Calcineurin 去磷酸化暴露 NLS 入核；在 T 细胞与心肌肥大中关键。',
  PLCB1: '磷脂酶 Cβ1，Gq/11 途径效应酶：水解 PIP2 → IP3 + DAG。',
  PLCG1: 'PLCγ1，RTK 底物（被磷酸化 Tyr783 激活），产生 IP3/DAG 双信使。',
  CACNA1C: 'L 型钙通道 Cav1.2（α1C 亚基），去极化门控钙内流，β 受体-PKA 正调节位点。',
  ATP2A2: 'SERCA2，ER 钙泵（Ca²⁺-ATPase），将胞质钙回收至 ER；受 PLB（受 PKA 磷酸化调控）抑制。',
  STIM1: 'ER 钙传感器，钙库耗竭后寡聚转位至质膜-ER 接触点激活 ORAI1（SOCE）。',
  ORAI1: 'CRAC 通道孔道亚基，STIM1 门控，介导钙库操控性钙内流。',
  MYLK: 'MLCK，Ca²⁺/CaM 依赖激酶，磷酸化肌球蛋白轻链触发平滑肌收缩。',
  // ============ Wnt / Notch / TGF-β ============
  WNT3A: 'Wnt 家族分泌糖蛋白（脂质化修饰），经典 Wnt/β-catenin 通路的原型配体。',
  FZD7: 'Frizzled7，七次跨膜 Wnt 受体，胞外富含半胱氨酸域（CRD）结合 Wnt。',
  LRP6: 'LDL 受体相关蛋白 6，Wnt 共受体，磷酸化后招募 Axin 至膜释放 β-catenin。',
  DVL1: 'Dishevelled，Wnt 信号中枢支架蛋白，招募 AXIN/GSK3 复合体至膜受体，解除对 β-catenin 的降解。',
  CTNNB1: 'β-catenin，双功能分子（粘附连接/信号）。免于降解后入核结合 TCF/LEF 驱动转录。',
  APC: '腺瘤性息肉病蛋白，β-catenin 破坏复合体核心（>80% 结肠癌截断突变）。',
  AXIN1: '破坏复合体支架，协调 APC/GSK3β/CK1 对 β-catenin Ser45/Thr41/Ser37/Ser33 依次磷酸化。',
  TCF7L2: 'T 细胞因子 4，HMG 盒转录因子，β-catenin 的核内伴侣（TCF/LEF 家族主要成员）。',
  LEF1: '淋巴细胞增强子结合因子 1，与 β-catenin 组装转录激活复合体。',
  CCND1: 'Cyclin D1，G1/S 转换限速因子（CDK4/6 激活子），Wnt 与 ERK 通路的汇聚靶基因。',
  DLL1: 'Delta-like 配体 1，膜结合 Notch 配体（DSL 域结合相邻细胞 Notch 受体）。',
  DLL4: 'Delta-like 4，血管内皮 Notch 配体，VEGF 信号的负缓冲。',
  JAG1: 'Jag1 配体，与 Delta 竞争结合 Notch，但对 Fringe 糖基化修饰不敏感。',
  NOTCH1: 'Notch 受体（单次跨膜），S2 (ADAM) + S3 (γ-secretase) 顺序切割释放 NICD；T-ALL 中 NOTCH1 激活突变。',
  ADAM10: 'ADAM 金属蛋白酶（S2 切割），配体牵拉变构后切除 Notch 胞外域。',
  ADAM17: 'TACE/ADAM17，S2 切割酶之一，亦介导 TNF 释放。',
  PSEN1: '早老素 1，γ-分泌酶催化亚基，行 S3 切割产生 NICD；家族性 AD 突变位点。',
  NCSTN: 'Nicastrin，γ-分泌酶复合体亚基（底物识别/稳定）。',
  PSENEN: 'Pen-2，γ-分泌酶小亚基，参与催化核心成熟。',
  APH1A: '前咽缺陷蛋白 1，γ-分泌酶组装亚基。',
  RBPJ: 'CSL/RBP-Jκ，序列特异 DNA 结合蛋白。无 NICD 时招募 HDAC/NCoR 抑制转录，NICD 结合后转变为激活子。',
  MAML1: 'Mastermind-like 1，NICD-RBPJ 复合体的共激活子，招募 p300/CBP。',
  HES1: 'bHLH 转录抑制子（Notch 直接靶基因），抑制组织特异性 bHLH 激活子（如 MyoD）维持祖细胞态。',
  HEY1: 'HES 相关 bHLH 抑制子，心血管发育中 Notch 效应分子。',
  KAT2B: 'p300/CBP 相关因子（PCAF），组蛋白乙酰转移酶，松弛染色质开放转录。',
  TGFBR1: 'TGF-β I 型受体（ALK5），被 II 型受体磷酸化 GS 域后激活，磷酸化 R-Smad。',
  TGFBR2: 'TGF-β II 型受体，组成性活性激酶；先结合配体再招募并磷酸化 I 型受体。',
  SMAD2: 'R-Smad（受体调节型），C 端 SSXS 基序被 TGFBR1 磷酸化后与 SMAD4 二聚入核。',
  SMAD3: 'R-Smad，与 SMAD2 冗余但亦独立介导细胞周期阻滞（p15/p21）。',
  SMAD4: 'Co-Smad（共同介质），与 R-Smad 二聚后结合 SME DNA 元件 + FoxH1/Sp1 辅因子。',
  SMAD7: 'I-Smad（抑制型），与 R-Smad 竞争受体结合位点并招募 Smurf E3 泛素连接酶（负反馈）。',
  SMAD6: 'I-Smad（抑制型），MH2 域竞争结合活化受体的 L3 环口袋，阻断 R-Smad 磷酸化；TGF-β 信号的自诱导负反馈。',
  SMURF2: 'HECT 型 E3 泛素连接酶，降解受体与 SMAD2（TGF-β 信号衰减器）。',
  ID1: 'Id1（DNA 结合抑制子 1），HLH 蛋白缺乏碱性域，封隔 bHLH 转录因子（如 MyoD/E2A）——维持增殖、阻断分化。',
  BMP4: 'BMP-4，TGF-β 超家族骨形态发生蛋白，经 ACVR2A/ACVR1 受体对磷酸化 SMAD1 传递成骨/胚胎模式信号。',
  INHBA: '抑制素 βA（Inhibin βA），与 α 亚基组成 inhibin 或同源二聚形成 activin，经 ACVR 受体磷酸化 SMAD2。',
  ACVR1: '激活素受体 I 型（ALK2），被 II 型受体磷酸化 GS 域后磷酸化 SMAD1/5/8（BMP 分支 R-Smad）。',
  ACVR2A: '激活素受体 II 型，组成性活性激酶，结合 activin/BMP 配体后招募并磷酸化 I 型受体。',
  SMAD1: 'BMP 分支 R-Smad，C 端 SSXS 被 ALK2/ALK3/ALK6 磷酸化后与 SMAD4 二聚入核（成骨基因程序）。',
  RBL1: 'p107 口袋蛋白（Rb 家族），低磷酸化态封隔 E2F；TGF-β 经 p15/p21 诱导 CDK 抑制使其维持抑制构象。',
  SKI: 'Ski 辅抑制子，招募 NCoR/HDAC 至 Smad 复合体 DNA 结合位点，将 TGF-β 信号转为转录沉默（肿瘤逃逸机制）。',
  SKIL: 'Ski 相关新基因（SnoN），与 Ski 冗余拮抗 Smad 转录；其降解速率决定 TGF-β 响应的时程。',
  FZD1: 'Frizzled1，七次跨膜 Wnt 受体，胞外富含半胱氨酸域（CRD）疏水槽结合 Wnt 脂质化残基。',
  LRP5: 'LDL 受体相关蛋白 5，Wnt 共受体（与 LRP6 同源），胞内 PPPSPxS 基序磷酸化后招募 Axin 至膜。',
  CSNK1A1: '酪蛋白激酶 1α（CK1α），破坏复合体首击激酶——磷酸化 β-catenin Ser45 为 GSK3β 继发磷酸化引物。',
  DKK1: 'Dickkopf-1，分泌型 Wnt 拮抗剂，结合 LRP5/6 并招募 Kremen 诱导内吞——Wnt 通路的可诱导负反馈基因。',
  SFRP1: '分泌型 Frizzled 相关蛋白 1，以 soluble CRD 假受体身份螯合 Wnt（旁分泌/自分泌拮抗环）。',
  WIF1: 'Wnt 抑制因子 1，分泌型脂质结合蛋白，直接螯合 Wnt 阻断其与 FZD/LRP 结合。',
  WNT5A: 'Wnt5a，非经典 Wnt（β-catenin 非依赖），经 ROR1/RYK 受体驱动平面细胞极性（PCP）与 Rho/Rac 信号。',
  FOSL1: 'Fra-1（FOS 样蛋白 1），AP-1 家族成员，Wnt/TCF 靶基因，替代 c-FOS 组成低转录活性 AP-1 变体。',
  PPARD: 'PPARβ/δ，核受体，Wnt 靶基因，与非磷酸化 β-catenin 竞争结合 TCF——促代谢/抗炎程序。',
  SOX17: 'SRY-box 17 转录因子，内胚层决定子；结合 TCF4 竞争性拮抗 β-catenin 转录（经典 Wnt 的刹车）。',
  CREBBP: 'CBP/p300，组蛋白乙酰转移酶，被 β-catenin/TCF 或 NICD/MAML 招募为通用共激活子（核内汇聚点）。',
  NLK: 'Nemo 样激酶（MAPK 家族），JNK 上游的非经典 Wnt 应答——磷酸化 TCF4 促其降解（Wnt 负调节）。',
  BAMBI: 'BMP 与激活素膜结合抑制子，假激酶受体——与 TGF-β/BMP 受体形成无功能二聚体（诱骗受体）。',
  LFNG: 'Lunatic Fringe，高尔基 Golgi β3-N-乙酰葡萄糖胺转移酶，糖基化 Notch EGF 重复——增强 Delta 信号、削弱 Jagged 信号。',
  NUMB: '内吞接头与细胞命运决定子，结合 Notch 胞内域促进其泛素化内吞降解（不对称分裂的分化信号）。',
  ITCH: 'ITCH/AIP4，HECT 型 E3 泛素连接酶，泛素化 Notch1 PEST 域促降解（配体非依赖性衰减）。',
  DTX1: 'Deltex E3 泛素连接酶，结合 NICD 的 ANK 重复域——既是 Notch 效应子又是其泛素化调节子。',
  SNW1: 'SKIP（ Ski 相互作用蛋白），转录剪接体组分，参与 NICD-RBPJ 激活复合体组装。',
  SPEN: 'SHARP（Spen 家族），大分子辅抑制子，招募 SMRT/HDAC 至 RBPJ 位点（无 NICD 时的默认抑制）。',
  ATXN1L: 'Ataxin-1 样蛋白，与 RBPJ/SMRT 互作，Notch 抑制网络的染色质层面调节因子。',
  HDAC1: '组蛋白去乙酰化酶 1，RBPJ 无 NICD 时的核心抑制子——去乙酰化关闭染色质（去抑制即激活的基础）。',
  TLE7: 'TLE/Groucho 家族辅抑制子，结合 TCF N 端——无 β-catenin 时将 Wnt 靶基因维持在关闭态。',
  CTBP1: 'CtBP（C 端结合蛋白），NADH 依赖辅抑制子，桥连 RBPJ/TCF 与 HDAC（代谢状态感知的转录抑制）。',
  NCOR2: 'SMRT/NCoR2 辅抑制子支架，招募 HDAC3 至无配体核受体与 RBPJ（Notch 默认抑制引擎）。',
  CIRSR: 'CIR（CSL 相互作用环指蛋白），RBPJ 抑制复合体的染色质重塑组分。',
  RITA1: 'RITA（RBPJ 与 TAB2 相互作用蛋白），连接 RBPJ 至 NF-κB/TAK1 模块（Notch-炎症交叉）。',
  NRARP: 'Notch 调节蛋白 ankyrin 重复，Notch 靶基因又反馈结合 NICD-RBPJ 限制信号强度（血管发育缓冲器）。',
  PTCRA: 'pre-TCRα，Notch 直接靶基因，T 细胞发育中 pre-TCR 复合体的组装限定组分。',
  SNAI1: 'Snai1 锌指转录抑制子，TGF-β-Smad3 诱导，抑制 E-cadherin 启动 EMT。',
  // ============ NF-κB / 凋亡 / p53 ============
  TNF: '肿瘤坏死因子-α，三聚体细胞因子，结合 TNFR1 后组装复合体 I（TRADD/TRAF2/RIPK1/cIAP）。',
  TNFRSF1A: 'TNFR1，死亡域受体。招募 TRADD 后双向输出：生存（NF-κB）或死亡（caspase-8）。',
  MYD88: '髓系分化因子 88，Toll/IL-1R 共同接头：IRAK4 相互作用域招募激酶级联。',
  TRAF6: 'TNFR 相关因子 6，K63 泛素 E3，组装 TAB2/TAK1 复合体（NF-κB 上游枢纽）。',
  IKBKB: 'IKKβ，NF-κB 抑制激酶复合体催化亚基，磷酸化 IκBα Ser32/36 触发其降解。',
  IKBKG: 'NEMO/IKKγ，IKK 复合体的调节骨架亚基（聚合泛素结合）。',
  NFKBIA: 'IκBα，Ankyrin 重复蛋白，遮蔽 NF-κB 的 NLS；被 IKK 磷酸化后经 β-TrCP 泛素化降解。',
  NFKB1: 'NF-κB p50 前体（p105），加工后与 RELA 二聚；Rel homology 域介导 DNA 结合。',
  RELA: 'p65/RelA，NF-κB 转录激活亚基（Ser536 磷酸化增强反式激活）。',
  TNFAIP3: 'A20，泛素编辑酶（去泛素化 + K48 泛素化 RIPK1/IKK），NF-κB 负反馈核心。',
  IL6: 'IL-6，NF-κB 靶细胞因子，驱动急性期反应与 JAK-STAT3 炎症轴。',
  FASLG: 'Fas 配体（FasL/CD95L），II 型跨膜蛋白（同源三聚体），细胞毒性 T 细胞的主要凋亡武器。',
  FAS: 'Fas/CD95，死亡域受体。配体结合三聚化后招募 FADD 组装 DISC。',
  FADD: 'Fas 相关死亡域接头，DED 域招募 procaspase-8（死亡效应域:死亡效应域同源互作）。',
  CASP8: 'Caspase-8，起始 caspase。DISC 高浓度下自剪切（D210→D216→D384）产生活性异源二聚体。',
  BID: 'BH3-only 蛋白，被 caspase-8 切割为 tBID 后嵌入线粒体外膜激活 BAX/BAK（外内源途径交汇点）。',
  BAX: 'Bcl-2 家族效应蛋白，BH3 激活后构象变化寡聚形成线粒体外膜孔（MOMP）。',
  BCL2: '抗凋亡 Bcl-2 家族首分子，隔离 BH3-only 蛋白与 BAX/BAK 维持线粒体完整（滤泡淋巴瘤 t(14;18) 靶基因）。',
  CYCS: '细胞色素 c，线粒体呼吸链电子载体；MOMP 释放后与 APAF1 羟基化结构域寡聚组装凋亡体。',
  APAF1: '凋亡蛋白酶激活因子，dATP + 细胞色素 c 触发车轮状七聚体凋亡体（procaspase-9 招募平台）。',
  CASP9: 'Caspase-9，凋亡体内起始 caspase（与 APAF1 CARD 结构域相互作用）。',
  CASP3: 'Caspase-3，主要执行 caspase。切割 PARP、ICAD/DFF45、波形蛋白等 300+ 底物，执行程序性拆解。',
  XIAP: 'X 连锁凋亡抑制子，BIR2 域直接抑制 caspase-3/7，BIR3 抑制 caspase-9（Smac/DIABLO 可解除）。',
  TP53: 'p53，基因组守卫转录因子（四聚体，序列特异 DNA 结合）。ATM/CHK2 磷酸化稳定其蛋白；~50% 人类肿瘤存在突变。',
  ATM: '共济失调毛细血管扩张突变激酶（PIKK 家族），DSB 感应器，磷酸化 p53 Ser15 与 CHK2 Thr68。',
  CHEK2: 'CHK2 检查点激酶，磷酸化 p53 Ser20（阻断 MDM2 结合）与 BRCA1。',
  CDKN1A: 'p21/Cip1，p53 经典靶基因：结合并抑制 Cyclin-CDK2/4 复合物 → G1 期阻滞。',
  BBC3: 'PUMA，p53 诱导的 BH3-only 蛋白（直接激活 BAX），凋亡阈值决定因子。',
  GADD45A: '生长阻滞 DNA 损伤诱导基因 45α，参与核苷酸切除修复与 G2/M 检查点。',
  // ============ mTOR / AMPK ============
  RHEB: '小 GTP酶（Ras 超家族），GTP 结合态直接激活 mTORC1；TSC 复合物是其 GAP。',
  RICTOR: 'Rictor，mTORC2 定义亚基，介导 Akt Ser473 磷酸化（PDK1 磷酸化 Thr308 之后）。',
  ULK1: 'ULK1 激酶，自噬起始复合体核心；mTORC1 磷酸化（Ser758）抑制其活性。',
  STK11: 'LKB1，AMPK 主要上游激酶（磷酸化 Thr172），Peutz-Jeghers 综合征抑癌基因。',
  PRKAA1: 'AMPK α1 催化亚基，Thr172 磷酸化激活；AMP 变构结合保护激活环。',
  PRKAB1: 'AMPK β1 调节亚基，糖原结合域 + ASC 结构域连接 α/γ。',
  ACACA: '乙酰辅酶 A 羧化酶 1（ACC1），脂肪酸合成限速酶；被 AMPK 磷酸化 Ser79 抑制。',
  PPARGC1A: 'PGC-1α，转录共激活子，AMPK 磷酸化后驱动线粒体生物合成程序。',
  SREBF1: 'SREBP-1c，脂质合成转录因子，受 mTORC1-AMPK 轴调控。',
  NTRK2: 'TrkB，BDNF 受体酪氨酸激酶，激活 PI3K-Akt/Ras-MAPK/PLCγ 三路信号。',

  // ---- mTOR / AMPK 通路补充 ----
  TSC1: 'Hamartin，TSC1/2 复合体的稳定亚基；与 TSC2（GAP）组成异二聚体，作为小 G 蛋白 Rheb 的负调控闸。',
  RPS6: '核糖体小亚基蛋白 S6，S6K1 磷酸化 Ser235/236/Ser240/244 后优先翻译 5′TOP mRNA（翻译机器组件）。',
  EIF4E: '真核翻译起始因子 4E，直接结合 mRNA 5′ 帽结构（m7GTP）——帽依赖翻译的限速步骤，受 4E-BP1 封锁。',

  // ---- NF-κB 通路补充 ----
  TLR4: 'Toll 样受体 4，LPS/内毒素模式识别受体；与 MD-2/CD14 组装后二聚化，启动 MyD88 与 TRIF 双臂 innate 免疫信号。',
  IRAK1: 'IL-1 受体相关激酶 1，受体近端 Ser/Thr 激酶；死亡域互作后自磷酸化激活，继而招募并激活 TRAF6。',
  MAP3K7: 'TAK1（TGF-β 激活性激酶 1），泛素支架激活的 MAP3K；磷酸化 MKK3/6/7 与 IKKβ，是 NF-κB/p38/JNK 三路枢纽。',
  BCL2L1: 'Bcl-xL，抗凋亡 BCL-2 家族成员；隔离 tBid/Bax 等BH3 促凋亡蛋白，维持线粒体外膜完整性（NF-κB 靶基因）。',

  // ---- 凋亡通路补充 ----
  PARP1: '聚 ADP 核糖聚合酶 1，DNA 修复传感器；被 Caspase-3 在 DEVD216 位点切割（24/89 kDa 片段）——凋亡的经典生物标记。',

  // ---- p53 通路补充 ----
  PMAIP1: 'NOXA（PMA 诱导蛋白 1），BH3-only 促凋亡蛋白；仅结合 Mcl-1/Bfl-1 释放 Bak，是 p53 应答的“执行臂”基因。',
  SESN1: 'Sestrin-1，p53 靶基因编码的代谢检查点蛋白；结合并抑制 p62/GATOR2 → 激活 AMPK，介导 p53-AMPK 代谢轴。',

  // ---- AMPK 通路补充 ----
  ADRA1A: 'α1A 肾上腺素能受体，Gq 耦联 GPCR；去甲肾上腺素 → PLCβ → IP3 → Ca²⁺ 升高，经由 CaMKKβ 交叉激活 AMPK。',

  // ---- Ca²⁺ 通路补充 ----
  ACh: '乙酰胆碱，胆碱能神经递质；毒蕈碱性受体（Gq）→ PLCβ → IP3 → Ca²⁺ 释放（平滑肌收缩/腺体分泌/心肌节律）。',
  C00076: 'Ca²⁺（游离钙离子），浓度梯度约 10⁴ 倍（ER ~1 mM vs 胞质 ~100 nM）；作为第二信使以“钙火花”形式传播。',
};

/**
 * 策划事件描述（键: "SRC>DST"，键中符号即 CoreNode id）
 * 覆盖 13 条通路核心级联的关键步骤，精确到残基与结构域
 */
export const CURATED_EVENTS: Record<string, string> = {
  // ---- MAPK: EGF → ERK 经典级联 ----
  'EGF>EGFR': 'EGF 以高亲和力（Kd≈1 nM）结合 EGFR 胞外 L2 域，诱导受体发生 2:2 二聚化（配体介导二聚）。',
  'EGFR>EGFR': 'EGFR 激酶域反式自磷酸化：C 端尾 Y992/Y1045/Y1068/Y1148/Y1173 依次磷酸化，生成 SH2 信号平台。',
  'EGFR>GRB2': 'GRB2 的 SH2 域以 pY1068-QPEY 基序结合 EGFR，SH3 域将 SOS 富脯氨酸区募集至质膜内侧。',
  'EGFR>SHC1': 'ShcA 被 EGFR 磷酸化（Y239/Y240/Y317），再招募 GRB2-SOS 复合体（信号放大支路）。',
  'SHC1>GRB2': 'pShc 的 PTB/pY 复合物招募 GRB2，级联信号从受体传递至接头网络。',
  'GRB2>SOS1': 'GRB2 双 SH3 域夹持 SOS1 的富脯氨酸基序，SOS 随接头转位至质膜内侧（膜定位即激活）。',
  'SOS1>KRAS': 'SOS1 的 CDC25 域催化 KRAS GDP→GTP 交换（~10⁵ 倍加速），KRAS 构象切换至 GTP 结合态。',
  'SOS1>HRAS': 'SOS 催化 HRAS 核苷酸交换，RAS-GTP 的 switch I/II 区暴露 RAF 结合面。',
  'HRAS>RAF1': 'RAS-GTP 以 μM 级亲和力结合 RAF1 RBD，使其从 14-3-3 抑制态释放并转位至膜。',
  'KRAS>RAF1': 'KRAS-GTP 结合 RAF1 的 RBD 域（R89），解除 N 端自抑制，RAF 在质膜上完全激活。',
  'KRAS>BRAF': 'KRAS-GTP 募集 BRAF，BRAF RBD 结合后二聚化获得完全激酶活性（RAF 二聚化为激活所需）。',
  'RAF1>MAP2K1': 'RAF1 磷酸化 MEK1 激活环 Ser218/Ser222，MEK1 催化活性提升 >1000 倍。',
  'BRAF>MAP2K1': 'BRAF 双磷酸化 MEK1 Ser218/Ser222（激活环），启动 MAPK 三级级联第二级。',
  'MAP2K1>MAPK1': 'MEK1 双磷酸化 ERK2 的 Thr-Glu-Tyr (T185/Y187) 基序——ERK 唯一的激活方式（双重特异性）。',
  'MAP2K2>MAPK3': 'MEK2 双磷酸化 ERK1 激活环 T202/Y204，ERK 进入完全活化构象。',
  'MAPK1>ELK1': 'ERK2 磷酸化 ELK1 的 DBD 附近 Ser383，ELK1 DNA 结合与反式激活能力大幅增强。',
  'MAPK1>FOS': 'ERK2 磷酸化 c-FOS 稳定其蛋白（Thr232 等），并协同 RSK 磷酸化 TAD 域延长半衰期。',
  'ELK1>FOS': 'pELK1 与 SRF 共同结合 c-fos 启动子血清反应元件（SRE: c-fos −320 区），启动即早基因转录。',
  'MAPK1>MYC': 'ERK 磷酸化 c-MYC Ser62（稳定）——GSK3β 随后磷酸化 T58（降解）构成稳定开关。',
  'FOS>JUN': 'c-FOS 与 c-JUN 经碱性拉链二聚化组成 AP-1 转录因子，结合 TPA 响应元件（TRE）。',
  'DUSP1>MAPK1': 'MKP-1/DUSP1 双特异性磷酸酶去除 ERK2 的 pThr/pTyr（T185/Y187），信号负反馈关闭。',
  'MAPK8>JUN': 'JNK 磷酸化 c-JUN Ser63/Ser73（氨基端），增强 AP-1 转录活性（应激分支）。',
  // ---- PI3K-Akt ----
  'IGF1>IGF1R': 'IGF-1 结合 IGF1R 胞外 CR 域诱导受体二聚化与激酶域反式自磷酸化。',
  'INS>INSR': '胰岛素结合 INSR，受体自磷酸化 7 个酪氨酸位点，IRS 接头随即被募集磷酸化。',
  'IGF1R>PIK3CA': 'pIRS/pY 接头结合 p85 SH2 域，解除对 p110 催化亚基的折叠抑制，PI3K 在膜上激活。',
  'PIK3CA>PIP3': 'PI3K 将 PIP2 5′位磷酸化为 PIP3；PIP3 作为脂质第二信使在膜内侧富集 PH 域蛋白。',
  'PDPK1>AKT1': 'PDK1 与 Akt 经各自 PH 域被 PIP3 招募并排，PDK1 磷酸化 Akt 激活环 Thr308。',
  'MTOR>AKT1': 'mTORC2 磷酸化 Akt 疏水基序 Ser473——Akt 完全激活所需的第二次磷酸化。',
  'AKT1>FOXO1': 'Akt 磷酸化 FOXO1 三个位点（T24/S256/S319），暴露 14-3-3 结合位点致其出核滞留胞质。',
  'AKT1>GSK3B': 'Akt 磷酸化 GSK3β N 端 Ser9（假底物机制），抑制其组成性激酶活性。',
  'AKT1>BAD': 'Akt 磷酸化 BAD Ser136，BAD 脱离 BCL-XL 转而结合 14-3-3——线粒体凋亡通道关闭。',
  'AKT1>TSC2': 'Akt 磷酸化 TSC2（Ser939/T1462），TSC1/2 GAP 失活→Rheb 保持 GTP 态→mTORC1 激活。',
  'PTEN>PIK3CA': 'PTEN 使 PIP3 去磷酸化恢复 PIP2，从源头截断 PI3K 信号（肿瘤抑制功能）。',
  'TSC2>RPTOR': 'TSC2 失活后 Rheb-GTP 激活 mTORC1，Raptor 开始递呈 S6K/4E-BP1 底物。',
  'RPS6KB1>EIF4EBP1': 'S6K1 交叉磷酸化 4E-BP1，与 mTORC1 直接磷酸化协同释放 eIF4E（帽依赖翻译全面启动）。',
  // ---- JAK-STAT ----
  'IL2>IL2RB': 'IL-2 结合 IL-2Rβ/γc 异源二聚体（高亲和力 Kd≈10 pM），受体- JAK 复合体变构聚集。',
  'IL2RB>JAK1': '受体箱 1 域（Box1 Pro-X-Pro 基序）相邻的 JAK1 发生交叉磷酸化（Y980/Y981 激活环）。',
  'IL2RG>JAK3': 'γc 链 Box1 域结合的 JAK3 交叉磷酸化激活，JAK1/JAK3 双激酶协同磷酸化受体尾部。',
  'JAK1>STAT5A': 'JAK1 磷酸化受体尾部 Tyr 供 STAT5 的 SH2 域停靠；随后 STAT5 自身 Y694/Y699 被磷酸化。',
  'JAK3>STAT5A': 'JAK3 磷酸化 STAT5a Tyr694，STAT5 经 SH2-pTyr 互换二聚化暴露 NLS 入核。',
  'JAK3>STAT5B': 'JAK3 磷酸化 STAT5B Y699，二聚体结合 GAS 元件（TTCNNNNAA）启动转录。',
  'STAT5A>MYC': 'pSTAT5 二聚体结合 c-myc 启动子 GAS 元件，驱动增殖基因第一波转录。',
  'STAT5A>BCL2L1': 'STAT5 结合 Bcl-xL 增强子，抑制凋亡为克隆扩增提供存活信号。',
  'STAT5A>SOCS1': 'STAT5 诱导 SOCS 基因表达——SOCS 蛋白随后结合 JAK 磷酸化位点关闭信号（负反馈延迟环）。',
  'SOCS1>JAK1': 'SOCS1 SH2 域结合 JAK1 激活环 pY980，同时 BOX 域延伸物招募 Elongin BC-Cul5-Rbx1 复合体泛素化 JAK。',
  'IFNG>IFNGR1': 'IFN-γ 同源二聚体交联 IFNGR1/IFNGR2，诱导 JAK1（α 链）/JAK2（β 链）交叉磷酸化。',
  'JAK1>STAT1': 'JAK1 磷酸化 IFNGR1 尾部 Tyr440/位供 STAT1 停靠；STAT1 Y701 被磷酸化后同源二聚。',
  'STAT1>IRF1': 'pSTAT1γ 二聚体（GAF）结合 IRF1 启动子 GAS 元件，IRF1 随后结合 ISRE 驱动干扰素刺激基因。',
  // ---- cAMP ----
  'EPI>ADRB2': '肾上腺素进入结合口袋：与 TM3 Asp113 盐桥 + TM5/6 Ser 相互作用，TM6 外旋 ~6 Å —— 受体转向活性构象。',
  'ADRB2>GNAS': '活性 β2-AR 胞内环与 Gsα 的 C 端 α5 螺旋铰链结合，GDP 释放、GTP 结合（G 蛋白循环启动）。',
  'GNAS>ADCY3': 'GTP-Gsα 的 switch II 区结合 AC 催化域 C2 槽，解离的 Gβγ 防止 AC 再结合——AC 催化 ATP 环化为 cAMP。',
  'cAMP>PRKACA': '两分子 cAMP 结合调节亚基的 BNBF 结构域，催化亚基解离——PKA 全酶四聚体解聚为活性单体。',
  'PRKACA>CREB1': 'PKA 催化亚基入核，磷酸化 CREB Ser133（KID 域），CBP/p300 经 KIX 域被招募。',
  'PRKACA>MAPK1': 'PKA 经 B-Raf/MEK 支路（cAMP→EPAC 交叉）调节 ERK 活性——信号串扰节点。',
  'CREB1>FOS': 'pCREB-CBP 复合体结合 c-fos 启动子的 CRE（−60 bp）与 SRE 协同启动即早基因。',
  'PDE4B>cAMP': 'PDE4 水解 cAMP 3′ 环磷酸二酯键生成 5′-AMP，第二信使浓度回落——信号终止。',
  'cAMP>RAPGEF3': 'cAMP 结合 EPAC1 的 cAMP 结合域（CBD），GEF 域暴露激活 Rap1（非 PKA 依赖通路）。',
  // ---- 钙信号 ----
  'ACh>PLCB2': '乙酰胆碱结合 M1 毒蕈碱型受体（GPCR），Gq 激活 PLCβ2 水解 PIP2 产生 IP3 + DAG。',
  'GNAQ>PLCB2': 'Gqα-GTP 的 switch 区插入 PLCβ2 的 C 端螺旋，将其招募至膜并激活 ~1000 倍。',
  'PLCB2>ITPR1': 'IP3 扩散至 ER，结合 IP3R1 氨基端配体结合域（LBD），通道四聚体变构开放释放 Ca²⁺。',
  'ITPR1>CALM1': 'ER 钙释放使胞质 [Ca²⁺] 从 ~100 nM 跃升至 ~1 μM，4 个 Ca²⁺ 协同结合钙调蛋白 EF-hand。',
  'CALM1>CAMK2A': 'Ca²⁺/CaM 包裹 CaMKII 调节段释放催化域；相邻亚基 Thr286 自磷酸化锁定自主活性（>1 s 记忆）。',
  'CALM1>PPP3CA': 'Ca²⁺/CaM 结合 Calcineurin B 亚基 + 暴露 A 亚基催化域，PP2B 磷酸酶活性激活。',
  'PPP3CA>NFATC1': 'Calcineurin 去磷酸化 NFAT 的 SRR1/SP2 重复区（13 个 Ser/Thr），暴露 NLS → 入核。',
  'NFATC1>IL2': 'NFAT 与 AP-1 协同结合 IL2 启动子 ARRE-2 元件——IL-2 转录的钙/钙调磷酸素依赖分支。',
  'CAMKK2>PRKAA1': 'CaMKKβ 磷酸化 AMPKα Thr172（与 LKB1 通路平行），钙信号与能量传感在此交叉。',
  'ATP2A2>CALM1': 'SERCA 泵将 Ca²⁺ 以 2:1 Ca²⁺/ATP 计量回收至 ER，胞质钙回落，信号复位。',
  'CACNA1C>CALM1': 'L 型通道去极化开放，Ca²⁺ 内流（CICR 触发源），CaM 的 C 端小叶预结合通道 IQ 域。',
  'RYR2>CALM1': 'RyR2 释放大量 ER 钙（心肌 CICR 放大 10 倍），钙瞬升触发收缩装置。',
  // ---- Wnt ----
  'WNT3A>FZD7': 'Wnt3a 的棕榈油酸（Ser209 酰化）插入 Fz7 CRD 疏水槽，同时结合 LRP6——三元配体-受体复合物形成。',
  'WNT3A>LRP6': 'Wnt 同时结合 LRP6 胞外 β 螺旋桨域，触发 LRP6 内吞聚集形成 "信号体"（signalosome）。',
  'FZD7>DVL1': 'Fz7 变构使其胞内 KTxxxW 基序结合 DVL PDZ 域，DVL 聚合形成信号体支架。',
  'DVL1>AXIN1': 'DVL 招募 Axin 至 LRP6 磷酸化的 PPPSPxS 基序，破坏复合体解体，GSK3β 停止磷酸化 β-catenin。',
  'GSK3B>CTNNB1': '破坏复合体（Axin/APC/GSK3β/CK1）依次磷酸化 β-cat S45→S41/S37/S33，β-TrCP 泛素化→蛋白酶体降解。',
  'CTNNB1>TCF7L2': '游离 β-catenin 入核（无经典 NLS，借 importin-α 直接转运），取代 Groucho 结合 TCF4。',
  'CTNNB1>LEF1': 'β-catenin 的 Arm 重复域结合 LEF1 N 端，招募 BCL9/PYGO/BCL10 激活复合体。',
  'TCF7L2>MYC': 'β-cat/TCF4 结合 c-myc 增强子（TBE 保守元件），驱动细胞周期引擎基因。',
  'TCF7L2>CCND1': 'TCF/β-cat 复合体结合 Cyclin D1 启动子，G1/S 转换速率上调（干细胞样增殖程序）。',
  'AXIN1>CTNNB1': 'Axin 支架将 GSK3β/CK1 与 β-cat 以近邻计量预组织，磷酸化降解效率提升 ~10⁴ 倍。',
  // ---- Notch ----
  'DLL1>NOTCH1': 'DLL1 的 DSL 域结合相邻细胞 Notch1 的 EGF-like 11-12 域，机械牵拉暴露 S2 切割位点。',
  'JAG1>NOTCH1': 'Jag1（Fringe 不敏感型配体）结合 Notch，诱导负向拉力暴露 ADAM 切割位点。',
  'ADAM10>NOTCH1': 'ADAM10 行 S2 切割：切除 Notch 胞外域（NECD 被配体 "拉走"），暴露 S3 位点。',
  'PSEN1>NOTCH1': 'γ-secretase（PSEN1 催化核心）行 S3 切割于膜内，释放 Notch 胞内域 NICD 入胞质。',
  'NCSTN>NOTCH1': 'Nicastrin 识别 S2 后的 N 端短肽递呈至 γ-secretase 催化裂缝，完成逆式跨膜水解。',
  'NOTCH1>RBPJ': 'NICD 的 RAM 域 + ANK 重复域结合 CSL(RBPJ) 的 BTD 与 CTD，取代 SMRT/HDAC 抑制复合体。',
  'MAML1>RBPJ': 'MAML1 以 N 端延伸肽形成 W 转角包裹 NICD-ANKK，招募 p300/CBP 组蛋白乙酰转移酶。',
  'RBPJ>HES1': 'NICD/RBPJ/MAML 激活复合体结合 HES1 启动子的成对 CSL 位点，转录去抑制。',
  'RBPJ>HEY1': 'CSL 复合体驱动 HEY1 bHLH 转录，心血管谱系分化基因启动。',
  'HES1>MYC': 'HES1 结合 myc 启动子 N/E-box 抑制分化基因，维持祖细胞增殖态（自我更新程序）。',
  'NOTCH1>ADAM17': '配体机械牵拉使 Notch1 变构（负向拉力模型），暴露胞外 S2 位点——ADAM17/TACE 金属蛋白酶切除 NECD。',
  'ADAM17>PSEN1': 'S2 切割后的 Notch1（NEXT）成为 γ-分泌酶唯一已知膜内底物递呈形式——PSEN1 催化核心就位。',
  'PSEN1>NCSTN': 'γ-分泌酶四亚基中 Nicastrin 以 extracellular domain 识别 S2 后的短 N 端肽，将底物递呈至 PSEN1 催化裂缝。',
  'NCSTN>RBPJ': 'S3 膜内切割释放的 NICD（Notch 胞内域）经 importin-α 入核，RAM 域+ANK 重复结合 RBPJ 的 BTD/CTD。',
  'MAML1>HES1': 'MAML1 招募的 p300/CBP 使 HES1 启动子区组蛋白高频乙酰化——成对 CSL 位点转录爆发放大。',
  'HES1>HEY1': 'HES1 与 HEY1 构成 Notch 双臂抑制网络：前者 N/E-box 结合，后者 E-box 沉默组织特异性 bHLH（冗余保险）。',
  'HEY1>LFNG': 'Lunatic Fringe 在 Golgi 糖基化新生 Notch 的 EGF 重复——增强 Delta 类配体敏感性、削弱 Jagged 类（配体选择开关）。',
  // ---- TGF-β ----
  'TGFB1>TGFBR2': 'TGF-β1 二聚体交联两个 TGFRII（组成性活性激酶），形成的受体异源四聚体招募 TGFRI。',
  'TGFBR2>TGFBR1': 'TGFRII 磷酸化 TGFRI 的 GS 域（Ser165/…/Ser178 串），解除 GS 自抑制楔锁定。',
  'TGFBR1>SMAD2': 'ALK5 的 L3 环识别 SMAD2 的 MH2 基序（受体磷酸化基序 SSMS），磷酸化 C 端 SSXS。',
  'SMAD2>SMAD4': 'pSMAD2 暴露 MH2 的 L3/环螺旋表面，与 SMAD4 组成异源三聚体（2:1），入核。',
  'SMAD4>SERPINE1': 'Smad 复合体与 Sp1 协同结合 CAGA 盒（Smad 结合元件），PAI-1 转录上调（纤维化标志）。',
  'SMAD4>CDKN1A': 'Smad3/4-Sp1 复合体结合 p21 启动子，G1 停滞（上皮细胞生长抑制应答）。',
  'SMAD7>TGFBR1': 'SMAD7 的 MH2 域竞争结合 ALK5 与 SMAD2 的互作面，并招募 Smurf2 泛素化受体（双保险负反馈）。',
  'SMAD3>SNAI1': 'Smad3 结合 SNAI1 启动子（Smad 盒），Snai1 抑制 CDH1（E-cadherin）→ EMT 启动。',
  'SMAD4>ID1': 'Smad3/4 复合体结合 ID1 启动子的 SBE 位点，Id1 上调封隔 bHLH 因子——增殖维持、分化暂停。',
  'ID1>SMAD6': '靶基因应答开启的同时，Smad 复合体亦自诱导 SMAD6 转录——自调节负反馈环启动（I-Smad 延迟约 1-2h 峰值）。',
  'SMAD6>SMAD2': 'SMAD6 的 MH2 域以高亲和力占据活化 ALK5 的 L3 环口袋，竞争性排斥 SMAD2 靠近受体激酶域。',
  'SMAD6>SMURF2': 'SMAD6 的 PPXY 基序以 WW 域结合 SMURF2，将 E3 连接酶招募至受体复合体行泛素化降解。',
  // ---- Wnt（经典 β-catenin 路线，键用核心子图节点 id）----
  'WNT3A>FZD1': 'Wnt3a 的棕榈油酸（Ser209 酰化）插入 Fz1 CRD 疏水槽，同时交联 LRP5——三元配体-受体复合物形成。',
  'WNT3A>LRP5': 'Wnt 同时结合 LRP5 胞外 β 螺旋桨域，触发 LRP5 内吞聚集形成 "信号体"（signalosome）。',
  'FZD1>LRP5': 'Fz1 与 LRP5 被同一 Wnt 分子交联为紧密二聚体，胞内段相互靠近启动磷酸化级联。',
  'FZD1>DVL1': 'Fz1 变构使其胞内 KTxxxW 基序结合 DVL PDZ 域，DVL 聚合形成信号体支架。',
  'LRP5>DVL1': 'LRP5 胞内磷酸化 PPPSPxS 簇与 Fz1-DVL 支架聚合——signalosome 半径内 Axin 被高浓度竞争捕获。',
  'AXIN1>GSK3B': 'Axin 支架将 GSK3β/CK1 与 β-cat 以近邻计量预组织，磷酸化降解效率提升 ~10⁴ 倍（复合体解体后失效）。',
  'CCND1>DKK1': 'Wnt 信号经 TCF 诱导 DKK1 转录（自调节负反馈环）——DKK1 分泌后结合 LRP5 封锁后续 Wnt 输入。',
  // ---- NF-κB ----
  'TNF>TNFRSF1A': 'TNF 三聚体交联 TNFR1 三个胞外域，受体聚集 Death 域招募 TRADD。',
  'TNFRSF1A>TRADD': 'TRADD 死亡域与 TNFR1 死亡域同源二聚（DD:DD 折叠），组装复合体 I。',
  'TRAF6>MAP3K7': 'K63 泛素链脚手架招募 TAB2/TAB3，TAK1 (MAP3K7) 磷酸化激活。',
  'MAP3K7>IKBKB': 'TAK1 磷酸化 IKKβ 激活环 Ser177/Ser181，IKK 复合体激活。',
  'IKBKB>NFKBIA': 'IKKβ 磷酸化 IκBα Ser32/Ser36 → β-TrCP SCF 泛素化 → 26S 蛋白酶体快速降解（t½<10 min）。',
  'NFKBIA>RELA': 'IκBα 降解暴露 p65/p50 的 NLS 与 RHD DNA 结合面，NF-κB 入核结合 κB 位点。',
  'RELA>IL6': 'NF-κB 结合 IL6 启动子 κB 位点（与 AP-1/NFAT 协同），炎症程序全面启动。',
  'TNFAIP3>IKBKG': 'A20 去泛素化 NEMO 的 K63 链并给 RIPK1 挂 K48 链——双重机制终止 NF-κB（负反馈）。',
  'MYD88>IRAK1': 'MyD88 的 TIR 域二聚后，死亡域招募 IRAK1/IRAK4 激酶二聚体，磷酸化级联启动。',
  // ---- 凋亡 ----
  'FASLG>FAS': 'FasL 同源三聚体交联三个 Fas 受体，Death 域聚集形成 DISC 平台。',
  'FAS>FADD': 'Fas 的 Death 域与 FADD 的死亡域同源结合，FADD 的 DED 域向外呈递。',
  'FADD>CASP8': 'procaspase-8 的 DED 域与 FADD DED 结合并二聚（局部高浓度），自剪切激活（链式：D373 切割释放 p18/p10）。',
  'CASP8>BID': 'caspase-8 切割 BID（D59 位），tBID 的 BH3 螺旋暴露插入线粒体外膜——外/内源途径交汇。',
  'BID>BAX': 'tBID 直接激活 BAX：α6 螺旋插入外膜，BAX 寡聚形成脂质孔（MOMP）。',
  'BAX>CYCS': '线粒体外膜通透化（MOMP）后细胞色素 c 完全释放至胞质——凋亡不可逆转折点（point of no return）。',
  'CYCS>APAF1': 'Apaf-1 的 WD40 域结合 cyto c + dATP → 车轮状凋亡体（heptamer）寡聚，CARD 域招募 procaspase-9。',
  'APAF1>CASP9': '凋亡体内的 procaspase-9 CARD 二聚获得活性（无需剪切即可活化的 "近邻激活"）。',
  'CASP9>CASP3': 'caspase-9 切割 procaspase-3（D175 位），产生 p17/p12 大小亚基组装成活性执行 caspase。',
  'CASP3>CASP6': '执行级联放大：caspase-3 切割并激活 caspase-6（反馈切割 caspase-8 形成环）。',
  'CASP3>CASP7': 'caspase-3 激活 caspase-7，两执行者共同切割 300+ 底物（PARP、ICAD、核纤层蛋白）。',
  'BCL2>BAX': 'BCL-2 的 BH1-3 沟捕获 BAX 的 BH3 螺旋——凋亡效应被隔绝（线粒体完整性维持）。',
  'TP53>BBC3': 'p53 结合 PUMA 启动子反应元件（p53 RE），PUMA 蛋白取代 BCL-2 沟内的 BH3-only 蛋白——凋亡阈值击穿。',
  'TP53>PMAIP1': 'p53 反式激活 NOXA，选择性抑制 MCL-1——为 BAX/BAK 激活扫清抑制障碍。',
  'CASP8>CFLAR': 'c-FLIP 竞争 FADD 结合位点抑制 DISC（caspase-8 的内源拮抗剂）。',// ---- p53 ----
  'ATM>TP53': 'DSB 激活的 ATM（MRN 复合体招募）磷酸化 p53 Ser15 + MDM2 Ser395。',
  'CHEK2>TP53': 'CHK2 磷酸化 p53 Ser20——MDM2 结合界面被破坏，p53 半衰期从分钟延长至小时。',
  'CHEK2>MDM2': 'CHK2 磷酸化 MDM2 使其与 p53 解离并自身出核降解。',
  'TP53>MDM2': 'p53 反式激活 MDM2 转录——MDM2 蛋白随后泛素化 p53（经典负反馈延迟环）。',
  'TP53>CDKN1A': 'p53 四聚体结合 p21 启动子两个保守 RE（5′-PuPuPuCWWGPyPyPy-3′），CDK2/4 被抑制 → G1 阻滞。',
  'TP53>GADD45A': 'p53 诱导 GADD45（与 PCNA 相互作用促进核苷酸切除修复）。',
  'TP53>BAX': 'p53 结合 BAX 启动子 RE，BAX 转录上调——若损伤不可修复，线粒体凋亡程序启动。',
  'MDM2>TP53': 'MDM2 RING 域催化 p53 多泛素化，26S 蛋白酶体降解——p53 基础周转（半衰期 ~20 min）。',
  // ---- mTOR / AMPK ----
  'RHEB>MTOR': 'Rheb-GTP 的 switch 区域结合 mTORC1 的 FKBP12-Rapamycin 结合域附近，变构提升激酶活性 ~5 倍。',
  'MTOR>RPS6KB1': 'mTORC1 磷酸化 S6K1 的疏水基序 Thr389（Raptor 递呈 TOS 基序）。',
  'MTOR>EIF4EBP1': 'mTORC1 逐步磷酸化 4E-BP1（Thr37/46 引导 → Ser65/Thr70 释放），eIF4E 解离。',
  'AKT1>TSC2>': '（冗余键保护）',
  'TSC2>MTOR': 'TSC 复合体失活后，Rheb-GTP 累积激活 mTORC1——蛋白合成机器全速运转。',
  'PRKAA1>MTOR': 'AMPK 磷酸化 Raptor Ser792 直接抑制 mTORC1，同时磷酸化 TSC2 Ser1345 强化其 GAP 活性。',
  'PRKAA1>ACACA': 'AMPK 磷酸化 ACC1 Ser79（SH2 域外的伪底物位点），脂肪酸合成即时关闭。',
  'STK11>PRKAA1': 'LKB1 组成型磷酸化 AMPKα Thr172——AMP 变构结合（γ 亚基）后保护该位点不被去磷酸化。',
  'CAMK2A>PRKAA1': 'CaMKKβ 以钙依赖方式磷酸化 AMPK Thr172（钙信号-能量交叉），独立于 LKB1。',
  'PRKAA1>ULK1': 'AMPK 磷酸化 ULK1 Ser317/Ser777 激活自噬启动（同时 mTORC1 的 Ser758 抑制被解除）。',
  'MTOR>ULK1': 'mTORC1 磷酸化 ULK1 Ser758，阻断其与 AMPK 的互作——营养丰富时自噬抑制。',

  // ---- mTOR 教学级联（hsa04150）----
  'AKT1>TSC1': 'Akt 磷酸化 TSC2（复合体 GAP 亚基）Ser939/Thr1462，TSC1/2 从溶酶体膜脱离——Rheb 的负调控闸解除。',
  'TSC1>RHEB': 'TSC1/2 复合体的 TSC2 亚基作为 GAP，催化 Rheb-GTP → Rheb-GDP（保持“关”态；失活后 Rheb 重新装载 GTP）。',
  'RPS6KB1>RPS6': 'S6K1 磷酸化 RPS6 Ser235/Ser236（对 5′TOP mRNA 翻译的“核糖体密码”），Ser240/244 随后加强。',
  'RPS6>EIF4EBP1': 'mTORC1 的第二条翻译臂：与 S6K 并行，直接多位点磷酸化 4E-BP1（Thr37/46 → Ser65/Thr70）。',
  'EIF4EBP1>EIF4E': '磷酸化的 4E-BP1 从 eIF4E 的 acidic face 解离（先 Thr37/46 引导后 Ser65 触发），eIF4E 释放 5′ 帽结合位点。',
  'EIF4E>ULK1': '第三条输出臂：mTORC1 通过 ULK1 复合体控制自噬闸门——营养丰富时磷酸化抑制，饥饿时交给 AMPK 激活。',

  // ---- NF-κB 教学级联（hsa04064）----
  'TLR4>MYD88': 'TLR4 二聚体的 TIR 域与 MyD88 C 端 TIR 域同源互作，经由 IRAK4 桥接将接头定位至受体胞内面。',
  'IRAK1>TRAF6': '自磷酸化的 IRAK1 变构释放死亡域，招募 TRAF6——泛素 E3 连接酶支架启动 K63 链自泛素化。',
  'RELA>BCL2L1': 'p65/p50 二聚体结合 BCL2L1 启动子 κB 位点（5′-GGRNNYYCC-3′），存活程序转录开启。',
  'BCL2L1>TNFAIP3': '同一 κB 位点家族也诱导 A20（TNFAIP3）——它将拆除本次信号本身的 K63 泛素链（延迟负反馈）。',

  // ---- 凋亡教学级联（hsa04210）----
  'CASP3>PARP1': 'Caspase-3 在 PARP1 的 DEVD216 位点切割出 24/89 kDa 片段——DNA 修复停摆，核骨架与基因组拆解开始。',

  // ---- p53 教学级联（hsa04115）----
  'ATM>CHEK2': 'ATM 磷酸化 CHK2 Thr68（SQ/TQ 基序），二聚体交叉自磷酸化后完全激活——检查点中继启动。',
  'CDKN1A>BBC3': 'p21（阻滞）之外，p53 同时转录 PUMA——若损伤不可修复，细胞走向“退出”分支。',
  'BBC3>PMAIP1': 'PUMA 与 NOXA 双 BH3 基因协同：PUMA 释放 Bax/Bak，NOXA 降解 Mcl-1——线粒体外膜 permeabilization 双保险。',
  'PMAIP1>SESN1': '第三分支：Sestrin 代谢检查点——p53 经 SESN1-GATOR2-AMPK 轴将“停止增殖”与“代谢降档”绑定。',
  'SESN1>MDM2': '应激解除后，p53 的靶基因 MDM2（E3 泛素连接酶）反噬 p53——泛素化降解，信号回到基线。',

  // ---- AMPK 教学级联（hsa04152）----
  'ADRA1A>CAMKK2': 'α1-AR-Gq → PLCβ → IP3 → Ca²⁺ 微域升高 → Ca²⁺/CaM 变构激活 CaMKKβ（钙信号交叉进入能量轴）。',
  'ACACA>TSC2': '关闭脂质合成后，AMPK 进一步磷酸化 TSC2 Ser1345 强化 GAP 活性——双保险关闭 mTOR 合成代谢。',
  'TSC2>RHEB': 'TSC2 GAP 催化 Rheb-GTP 水解；AMPK 强化后的 TSC1/2 将 Rheb 钓在 GDP 态——生长开关“断电”。',
  'ULK1>PPARGC1A': '自噬回收原料的同时，AMPK 直接磷酸化 PGC-1α（能量应激的双重准备：回收 + 重建产能）。',

  // ---- Ca²⁺ 教学级联（hsa04020）----
  'ACh>PLCB1': 'ACh 结合毒蕈碱性受体 → Gq 变构交换 GTP → Gαq 结合 PLCβ（替代性：受体-效应酶直接耦合）。',
  'PLCB1>ITPR1': 'PLCβ 水解 PIP2 生成 IP3 + DAG；IP3 扩散至 ER 膜结合 IP3R 胞外调节域（N 端 suppressor 域并合）。',
  'ITPR1>C00076': 'IP3 结合触发 IP3R 四聚体通道开放：ER 钙库（~1 mM）顺梯度涌出，局部胞质钙升高 10-50 倍。',
  'C00076>RYR2': 'Ca²⁺ 直接结合 RyR2 胞质侧 E-F 手位点 → CICR（钙诱导钙释放）：信号以“钙火花”形式放大传播。',
  'CAMK2A>PPP3CA': '钙调蛋白将信号分拣：高频钙振荡 → CaMKII（频率解码）；持续低频 → Calcineurin（持续时间解码）。',
  'NFATC1>ATP2A2': '信号复位：SERCA 以 2 Ca²⁺/ATP 将钙泵回 ER，胞质钙回落至 ~100 nM——NFAT 信号窗口关闭。',
};

/** 查找策划事件（支持 source/target 任一方向的别名归一化在引擎层完成） */
export function getCuratedEvent(source: string, target: string): string | undefined {
  return CURATED_EVENTS[`${source}>${target}`];
}

/** 通用兜底注释生成 */
export function fallbackNote(label: string, kind: string, compartment: string): string {
  const kindZh: Record<string, string> = {
    ligand: '信号配体', receptor: '膜受体', kinase: '蛋白激酶', phosphatase: '磷酸酶',
    adapter: '接头蛋白', gtpase: '小 GTP 结合蛋白', tf: '转录因子', gene: '靶基因',
    compound: '第二信使/代谢物', channel: '离子通道', enzyme: '信号酶分子', other: '信号分子',
  };
  const compZh: Record<string, string> = {
    extracellular: '细胞外基质', membrane: '细胞膜', cytoplasm: '细胞质', nucleus: '细胞核',
  };
  return `${label} 是 ${compZh[compartment] ?? compartment} 中的${kindZh[kind] ?? '信号'}分子，参与本通路的信号转导网络。`;
}
